title: "MuseV: Infinite-length and High Fidelity Virtual Human Video Generation with Visual Conditioned  Parallel Denoising"
description: MuseV's Introduction blog

url: https://long-haul.netlify.app
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: / # Ex: /project-page
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Generation Galary
      url: /home


# social:
#     github: brianmaierjr
#     twitter: brianmaierjr
#     facebook: brianmaierjr
#     email: brimaidesigns@gmail.com
#     linkedin: brianmaierjr
#     youtube: RickAstleyYT
#     tumblr: i-am-a-fish

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
